# noinspection SqlResolveForFile
# noinspection SqlNoDataSourceInspectionForFile

SELECT TO_CHAR(DT, 'YYYYMMDD'), SUM(DT) FROM A WHERE DT >= (SELECT TO_DATE(XXXX, 'YYYYMMDD') FROM B) AND TO_CHAR(TO_DATE(DT, 'YYYYMMDD'), 'YYYY-MM-DD') = '2020-01-01';

SELECT TO_CHAR(DT, 'YYYYMMDD'), SUM(DT) FROM A WHERE DT >= (SELECT TO_DATE(XXXX, 'YYYYMMDD') FROM B) AND TO_CHAR(TO_DATE(DT, 'YYYYMMDD'), 'YYYY-MM-DD') = '2020-01-01'
UNION
SELECT TO_CHAR(DT, 'YYYYMMDD'), SUM(DT) FROM A WHERE DT >= (SELECT TO_DATE(XXXX, 'YYYYMMDD') FROM B) AND TO_CHAR(TO_DATE(DT, 'YYYYMMDD'), 'YYYY-MM-DD') = '2020-01-01';

SELECT * FROM A, B WHERE (DT + 1) = '2020-01-01' AND A.X + 1 = B.X AND TO_CHAR(DT + 1, 'YYYYMMDD') = 2;

SELECT * FROM A
  INNER JOIN B ON (A.ID = B.ID AND TO_CHAR(TO_DATE(DT, 'YYYYMMDD'), 'YYYY-MM-DD') = '2020-01-01')
WHERE 1 = (
  SELECT X FROM A, B WHERE (DT + 1) = '2020-01-01' AND A.X + 1 = B.X AND TO_CHAR(DT + 1, 'YYYYMMDD') = 2
);

SELECT
  CASE
  WHEN TO_CHAR(TO_DATE(DT, 'YYYYMMDD'), 'YYYY-MM-DD') > 1 THEN 1
  ELSE 0
  END
FROM A
WHERE DT = TO_CHAR('2020-01-01', 'YYYYMMDD');