# noinspection SqlResolveForFile
# noinspection SqlNoDataSourceInspectionForFile

SELECT *
FROM A
WHERE ID NOT IN (SELECT ID FROM A_BAD);

SELECT *
FROM A
WHERE ID NOT IN (SELECT ID FROM A_BAD)

UNION

SELECT *
FROM A
WHERE ID NOT IN (SELECT ID FROM A_BAD)
;

SELECT *
FROM A AS A
WHERE NOT EXISTS (SELECT ID FROM A_BAD WHERE ID = A.ID);
